from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

styles = getSampleStyleSheet()


def create_verification_page(
    elements,
    report_id
):

    elements.append(
        Paragraph(
            "<font size=18 color='#003366'><b>Report Verification</b></font>",
            styles["Heading1"]
        )
    )

    elements.append(Spacer(1,15))

    verification = f"""

    <b>Report ID :</b> {report_id}<br/><br/>

    <b>Generated By :</b> Voltora<br/><br/>

    <b>Software Version :</b> Version 3.0<br/><br/>

    <b>Generated On :</b>

    {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}<br/><br/>

    <font color='green'><b>✓ VERIFIED REPORT</b></font>

    """

    elements.append(
        Paragraph(
            verification,
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1,25))