"""
GridGuard AI - Virtual Sensor System

Software simulation of:
- Voltage Sensor
- Current Sensor
- Temperature Sensor
- Frequency Sensor

These values are generated by the virtual circuit
and are later passed to the existing GridGuard AI model.
"""


def read_virtual_sensors(circuit_data):
    """
    Convert virtual circuit output into sensor readings.
    """

    voltage = float(circuit_data.get("Voltage", 0.0))
    current = float(circuit_data.get("Current", 0.0))
    frequency = float(circuit_data.get("Frequency", 50.0))
    temperature = float(circuit_data.get("Temperature", 30.0))

    return {
        "Voltage": round(voltage, 2),
        "Current": round(current, 2),
        "Frequency": round(frequency, 2),
        "Temperature": round(temperature, 2),
    }


def get_sensor_status(sensors):
    """
    Determine whether the virtual sensors are receiving
    valid electrical measurements.
    """

    voltage = sensors["Voltage"]
    current = sensors["Current"]
    frequency = sensors["Frequency"]
    temperature = sensors["Temperature"]

    if voltage == 0 and current == 0:
        return "🔴 NO ELECTRICAL SUPPLY"

    if voltage < 180:
        return "🟡 LOW VOLTAGE"

    if voltage > 260:
        return "🟣 HIGH VOLTAGE"

    if current > 15:
        return "🟠 HIGH CURRENT"

    if temperature > 60:
        return "🔴 HIGH TEMPERATURE"

    if frequency < 48 or frequency > 52:
        return "🟣 FREQUENCY ABNORMAL"

    return "🟢 SENSORS NORMAL"


def get_sensor_summary(sensors):
    """
    Create a display-friendly sensor summary.
    """

    return {
        "Voltage Sensor": f'{sensors["Voltage"]:.2f} V',
        "Current Sensor": f'{sensors["Current"]:.2f} A',
        "Frequency Sensor": f'{sensors["Frequency"]:.2f} Hz',
        "Temperature Sensor": f'{sensors["Temperature"]:.2f} °C',
    }